import type { AssetRef } from '@getbeak/extension-sdk';

import { EntryMap } from './body-editor-json';
import { ValueSections } from './values';

export interface RequestOverview {
	verb: string;
	url: ValueSections;
	query: Record<string, ToggleKeyValue>;
	headers: Record<string, ToggleKeyValue>;
	/**
	 * Path parameters declared by the source spec (OpenAPI `in: 'path'`).
	 * Optional — present only on linked-OpenAPI requests today. The request
	 * pane renders an inline editor section when this map is non-empty;
	 * flight prep substitutes `:name` in the URL value-parts with each
	 * entry's bound value before resolving variables. Hand-authored URLs
	 * don't populate this map (no spec to derive metadata from).
	 */
	pathParameters?: Record<string, PathParameter>;
	body: RequestBody;
	options: RequestOptions;
	/**
	 * Marks this file as the canonical introspection seed for its parent
	 * endpoint collection (currently set on the GraphQL `Introspection.json`
	 * created when a new endpoint folder is registered). Surfaced as a tab
	 * badge + request-pane banner so users don't repurpose the file as a
	 * normal request and lose the ready-to-fire schema query.
	 *
	 * Functionally a hint — Beak doesn't lock the file or change its
	 * behaviour; the GraphQL editor's autocomplete uses its own hardcoded
	 * introspection query regardless of this flag.
	 */
	introspection?: true;
	/**
	 * Set on files generated by a sync source (OpenAPI / gRPC today). Drives
	 * the linked badge on the tree row + re-sync skip behaviour. Auto-flips
	 * `linked: true → false` on the first user edit; users can re-link from
	 * the request-pane banner.
	 */
	_provenance?: {
		source: 'openapi' | 'grpc';
		linked: boolean;
		operationId?: string;
		syncedAt?: string;
	};
}

export type RequestBody =
	| RequestBodyText
	| RequestBodyJson
	| RequestBodyJsonRaw
	| RequestBodyUrlEncodedForm
	| RequestBodyFile
	| RequestBodyMultipart
	| RequestBodyGraphQl
	| RequestBodyGrpc;

export type RequestBodyType =
	| 'text'
	| 'json'
	| 'json_raw'
	| 'url_encoded_form'
	| 'file'
	| 'multipart'
	| 'graphql'
	| 'grpc';

export interface RequestBodyText {
	type: 'text';
	payload: string;
}

export interface RequestBodyJson {
	type: 'json';
	payload: EntryMap;
}

/**
 * JSON body authored as a raw string. Equivalent in payload terms to a
 * `text` body, but carries an `application/json` content type by default
 * and renders in a Monaco editor with JSON language highlighting. Pick this
 * when you want full control over the JSON text (and you're fine losing
 * Beak's structured-edit affordances + variable insertion).
 *
 * `schemaSeed` carries the EntryMap the user authored when this body was a
 * structured `json` body. We persist it across the json → json_raw switch
 * so (a) Monaco's JSON language service can validate the raw text against
 * a generated JSON Schema, and (b) the user can flip back to structured
 * mode without losing their schema (required / type / description /
 * options). On a fresh json_raw body the field is absent.
 */
export interface RequestBodyJsonRaw {
	type: 'json_raw';
	payload: string;
	schemaSeed?: import('./body-editor-json').EntryMap;
}

export interface RequestBodyUrlEncodedForm {
	type: 'url_encoded_form';
	payload: Record<string, ToggleKeyValue>;
}

export interface RequestBodyFile {
	type: 'file';
	payload: {
		fileReferenceId?: string;
		contentType?: string;
		/**
		 * Content-addressed pointer into the project's `_assets/` store. When
		 * present, this is the canonical source of bytes for flight execution;
		 * `fileReferenceId` stays for legacy projects but is read-only.
		 */
		assetRef?: AssetRef;
		/**
		 * Wire-only field populated by flight prep when the body resolves to
		 * a {@link import('@beak/common/types/value-producers').ValueProducerHandle}.
		 * For asset-backed bodies the requester reads from disk directly and
		 * the bytes never cross IPC.
		 */
		producer?: import('@beak/common/types/value-producers').ValueProducerHandle;
	};
}

/**
 * Multipart body — ordered list of parts, each independently typed (text or
 * binary). Lands per ADR-0007 § "Multipart as a first-class body type".
 *
 * `boundary` is optional; when absent, the requester picks a fresh
 * ksuid-derived boundary at flight time so users don't have to think about
 * collisions. Binary parts resolve via the resolver's `binary` sink, so they
 * accept any RTV that emits `bytes` / `asset` / `stream`. Asset-backed parts
 * read from disk in the requester and stream into node-fetch directly;
 * inline bytes pass through the IPC payload.
 */
export interface RequestBodyMultipart {
	type: 'multipart';
	payload: {
		/** Optional explicit boundary; defaults to a fresh ksuid at flight time. */
		boundary?: string;
		parts: MultipartPart[];
	};
}

export type MultipartPart = MultipartPartText | MultipartPartBinary;

export interface MultipartPartText {
	kind: 'text';
	name: ValueSections;
	value: ValueSections;
	/** Optional explicit Content-Type; defaults to `text/plain; charset=utf-8`. */
	contentType?: string;
}

export interface MultipartPartBinary {
	kind: 'binary';
	name: ValueSections;
	filename?: ValueSections;
	value: ValueSections;
	contentType?: ValueSections;
}

export interface RequestBodyGraphQl {
	type: 'graphql';
	payload: {
		query: string;
		variables: EntryMap;
	};
}

/**
 * gRPC method invocation payload — a saved call against a discovered service.
 * The endpoint URL + descriptor (reflection / proto / buf) come from the
 * parent endpoint folder's `_collection.json`; only the method picker and
 * request body live on the request file itself, so renaming a method on the
 * server doesn't quietly orphan request files (a missing method shows an
 * error at flight time rather than at the file-loader level).
 */
export interface RequestBodyGrpc {
	type: 'grpc';
	payload: {
		/** Fully-qualified service name, e.g. `helloworld.HelloService`. */
		service: string;
		/** RPC method on that service. */
		method: string;
		/** Request body, stored as a JSON string for round-tripping in the editor. */
		requestJson: string;
		/**
		 * Per-call gRPC metadata — the gRPC equivalent of HTTP headers. Sent
		 * on the request side; lowercase keys land on the wire. Binary
		 * metadata (`-bin` suffix in gRPC) takes base64 strings; the editor
		 * doesn't yet flag binary-vs-string but the wire layer handles
		 * either.
		 */
		metadata?: Record<string, string>;
	};
}

export interface RequestOptions {
	followRedirects: boolean;
	/** When true, the requester accepts gzip/deflate/br and decodes the body. */
	decompressResponse?: boolean;
	/** Request timeout in milliseconds; `0` (default) disables the timeout. */
	timeoutMs?: number;
	/** Cap on redirects followed when `followRedirects` is true. */
	maxRedirects?: number;
	/**
	 * Cookie opt-out. When `false`, no jars contribute cookies to the
	 * outgoing request. Defaults to `true`.
	 */
	sendCookies?: boolean;
	/**
	 * Variable-set names whose currently-selected item should layer extra
	 * cookies on top of the project's primary jar (e.g. `['User']`
	 * alongside the project default `Environment`). Names must match
	 * `variableSets` keys; unknown names are ignored at flight time.
	 */
	additionalCookieJarSets?: string[];
}

/**
 * Limited type set for scalar properties (headers, query, url-encoded form).
 * `token` is a UX hint that the editor should mask the value; on the wire
 * it serialises as a plain string.
 */
export type ScalarPropertyType = 'string' | 'number' | 'boolean' | 'enum' | 'token';

/**
 * Path-parameter entry — one per `{name}` placeholder declared by the source
 * spec on an OpenAPI operation. Mirrors {@link ToggleKeyValue} sans
 * `enabled`: path params are required by URL structure, so toggling them
 * off would only produce broken requests.
 */
export interface PathParameter {
	name: string;
	value: ValueSections;
	type?: ScalarPropertyType;
	required?: boolean;
	description?: string;
	options?: import('./body-editor-json').EnumOption[];
}

export interface ToggleKeyValue {
	name: string;
	value: ValueSections;
	enabled: boolean;
	/** Schema metadata — set in schema mode, ignored at flight time. */
	type?: ScalarPropertyType;
	required?: boolean;
	description?: string;
	/**
	 * For `type === 'enum'`, the allowed values. Value mode renders a select
	 * instead of a free-text input when this list is non-empty. Typed
	 * primitives (`string | number | boolean | null`) so enums like
	 * `[200, 404, 500]` keep their wire shape; the editor auto-detects the
	 * type from what the user types.
	 */
	options?: import('./body-editor-json').EnumOption[];
}
