import type { Provenance, RequestFile } from '../schemas';

/**
 * Read-only rules around request-file `_provenance` — the marker the OpenAPI /
 * gRPC sync writers stamp onto generated files so re-syncs know they're
 * allowed to overwrite. The rules below are the single source of truth;
 * scattering `node.info._provenance?.linked === true` checks across the
 * codebase invites drift (one place forgets the `=== true` and treats
 * `undefined` as truthy, another forgets the optional chain).
 *
 * Convention: a request is "linked to a spec" when `_provenance.linked`
 * is explicitly `true`. Missing `_provenance` (hand-authored requests)
 * and `_provenance.linked: false` (user-detached) both count as unlinked.
 */

/** Minimal shape needed for the linked check — works on both `RequestFile` and `RequestOverview`. */
interface HasProvenance {
	_provenance?: Provenance;
}

/**
 * `true` only when the request file was generated by a spec and has not
 * yet been detached by the user. The single canonical predicate — every
 * other "is this linked?" check in the codebase should call this rather
 * than spelling it out inline.
 */
export function isLinked(node: HasProvenance | null | undefined): boolean {
	return node?._provenance?.linked === true;
}

/**
 * Inverse of `isLinked` with a friendlier read at the call site. Returns
 * `true` for both never-linked and user-detached files.
 */
export function isUnlinked(node: HasProvenance | null | undefined): boolean {
	return !isLinked(node);
}

/**
 * Detach a request from its spec. Sets `_provenance.linked: false` so
 * re-syncs leave the file alone; preserves the original `source` and
 * `operationId` so a future re-link knows which spec entry to point at.
 * Idempotent — calling on an already-unlinked request just returns it.
 *
 * `defaultSource` is the source kind to stamp when the request has no
 * existing `_provenance` (i.e. it was hand-authored). Only matters for
 * the rare path of "user takes ownership of a hand-authored file";
 * normal flow always passes through a request that was previously
 * linked.
 */
export function unlinkRequest<T extends HasProvenance>(node: T, defaultSource: Provenance['source'] = 'openapi'): T {
	const existing = node._provenance;
	const next: Provenance = {
		source: existing?.source ?? defaultSource,
		linked: false,
		...(existing?.operationId ? { operationId: existing.operationId } : {}),
		...(existing?.syncedAt ? { syncedAt: existing.syncedAt } : {}),
	};
	return { ...node, _provenance: next };
}

/**
 * Strip `_provenance` entirely. Used when a file is being copied or
 * exported and should no longer be associated with its spec. Different
 * from `unlinkRequest` — that keeps the marker but flips `linked: false`;
 * this removes the marker completely.
 */
export function stripProvenance<T extends HasProvenance>(node: T): T {
	const { _provenance: _ignored, ...rest } = node;
	return rest as T;
}

/**
 * Type narrower for the loose `{ id?, linked? }` shape the OpenAPI writer
 * reads off disk. Lets host-side `re-sync should overwrite this file?`
 * logic share the same `isLinked` predicate the renderer uses, just with
 * a partially-parsed input. Returns `false` for unparseable / missing
 * inputs.
 */
export function isLinkedRawRecord(raw: { linked?: boolean } | null | undefined): boolean {
	return raw?.linked === true;
}

export type { Provenance, RequestFile };
