// Source of truth is @beak/state/extensions; this re-export keeps existing UI imports working.
import {
	checkExtensionUpdates,
	extensionRemoved,
	extensionUpsert,
	extensionsLoaded,
	installExtension,
	operationChanged,
	reloadExtensions,
	removeExtension,
	searchExtensions,
	searchStateChanged,
	startExtensions,
	updateExtension,
	updatesAvailable,
} from '@beak/state/extensions';

export {
	checkExtensionUpdates,
	extensionRemoved,
	extensionUpsert,
	extensionsLoaded,
	installExtension,
	operationChanged,
	reloadExtensions,
	removeExtension,
	searchExtensions,
	searchStateChanged,
	startExtensions,
	updateExtension,
	updatesAvailable,
};
export default {
	checkExtensionUpdates,
	extensionRemoved,
	extensionUpsert,
	extensionsLoaded,
	installExtension,
	operationChanged,
	reloadExtensions,
	removeExtension,
	searchExtensions,
	searchStateChanged,
	startExtensions,
	updateExtension,
	updatesAvailable,
};
