// Source of truth is @beak/core/preferences; this re-export keeps existing UI imports working.
import {
	editorPreferencesLoaded,
	editorPreferencesSetSelectedVariableGroup,
	loadEditorPreferences,
	loadProjectPanePreferences,
	loadRequestPreferences,
	loadSidebarPreferences,
	projectPanePreferenceSetCollapse,
	projectPanePreferencesLoaded,
	requestPreferenceSetReqJsonExpand,
	requestPreferenceSetReqMainTab,
	requestPreferenceSetResMainTab,
	requestPreferenceSetResPrettyLanguage,
	requestPreferenceSetResSubTab,
	requestPreferencesLoaded,
	sidebarPreferenceSetCollapse,
	sidebarPreferenceSetSelected,
	sidebarPreferencesLoaded,
} from '@beak/core/preferences';

export {
	editorPreferencesLoaded,
	editorPreferencesSetSelectedVariableGroup,
	loadEditorPreferences,
	loadProjectPanePreferences,
	loadRequestPreferences,
	loadSidebarPreferences,
	projectPanePreferenceSetCollapse,
	projectPanePreferencesLoaded,
	requestPreferenceSetReqJsonExpand,
	requestPreferenceSetReqMainTab,
	requestPreferenceSetResMainTab,
	requestPreferenceSetResPrettyLanguage,
	requestPreferenceSetResSubTab,
	requestPreferencesLoaded,
	sidebarPreferenceSetCollapse,
	sidebarPreferenceSetSelected,
	sidebarPreferencesLoaded,
};

export default {
	editorPreferencesLoaded,
	editorPreferencesSetSelectedVariableGroup,
	loadEditorPreferences,
	loadProjectPanePreferences,
	loadRequestPreferences,
	loadSidebarPreferences,
	projectPanePreferenceSetCollapse,
	projectPanePreferencesLoaded,
	requestPreferenceSetReqJsonExpand,
	requestPreferenceSetReqMainTab,
	requestPreferenceSetResMainTab,
	requestPreferenceSetResPrettyLanguage,
	requestPreferenceSetResSubTab,
	requestPreferencesLoaded,
	sidebarPreferenceSetCollapse,
	sidebarPreferenceSetSelected,
	sidebarPreferencesLoaded,
};
