// Source of truth is @beak/state/git; this re-export keeps existing UI imports working.
import {
	addBranch,
	changeSelectedBranch,
	gitClosed,
	gitOpened,
	operationDismissed,
	operationFailed,
	operationStarted,
	operationSucceeded,
	remotesUpdated,
	removeBranch,
	requestCheckout,
	requestCommit,
	requestFetch,
	requestPull,
	requestPush,
	requestStatus,
	startGit,
	statusFailed,
	statusFetched,
} from '@beak/state/git';

export {
	addBranch,
	changeSelectedBranch,
	gitClosed,
	gitOpened,
	operationDismissed,
	operationFailed,
	operationStarted,
	operationSucceeded,
	remotesUpdated,
	removeBranch,
	requestCheckout,
	requestCommit,
	requestFetch,
	requestPull,
	requestPush,
	requestStatus,
	startGit,
	statusFailed,
	statusFetched,
};

export default {
	addBranch,
	changeSelectedBranch,
	gitClosed,
	gitOpened,
	operationDismissed,
	operationFailed,
	operationStarted,
	operationSucceeded,
	remotesUpdated,
	removeBranch,
	requestCheckout,
	requestCommit,
	requestFetch,
	requestPull,
	requestPush,
	requestStatus,
	startGit,
	statusFailed,
	statusFetched,
};
